import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Cristian Diaz | Portafolio Full Stack",
  description: "Portafolio personal de Cristian Diaz: desarrollo full stack, interfaces modernas y experiencias web con estética espacial.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "cristian diaz",
    "desarrollador full stack",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Cristian Diaz",
  },
} as const;
